name: Deploy Supabase Functions

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'supabase/functions/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy to Supabase
        run: |
          supabase functions deploy telegram-notify --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
          supabase functions deploy telegram-webhook --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
          supabase functions deploy onesignal-send-notification --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
          supabase functions deploy onesignal-get-subscribers --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
